# Generated by Django 5.0.7 on 2024-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=50)),
                ('final', models.CharField(max_length=50)),
                ('poste_1', models.CharField(blank=True, max_length=5, null=True)),
                ('poste_2', models.CharField(blank=True, max_length=5, null=True)),
                ('poste_3', models.CharField(blank=True, max_length=5, null=True)),
                ('notas', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
